# Generated by Django 4.1.3 on 2022-11-12 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cafes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="review",
            name="review",
            field=models.TextField(blank=True, null=True),
        ),
    ]
