# Generated by Django 4.1.3 on 2022-11-13 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cafes", "0003_cafe_owner"),
    ]

    operations = [
        migrations.RenameField(
            model_name="review",
            old_name="user",
            new_name="author",
        ),
    ]
