# Generated by Django 4.1.3 on 2022-11-13 20:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("cafes", "0007_review_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="cafe",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cafe",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
